export const AUTH_REQUEST = "AUTH_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FETCH_TEAMS_REQUEST = "FETCH_TEAMS_REQUEST";
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_FAILURE = "FETCH_TEAMS_FAILURE";
export const FETCH_TEAM_DETAIL_REQUEST = "FETCH_TEAM_DETAIL_REQUEST";
export const FETCH_TEAM_DETAIL_SUCCESS = "FETCH_TEAM_DETAIL_SUCCESS";
export const FETCH_TEAM_DETAIL_FAILURE = "FETCH_TEAM_DETAIL_FAILURE";
export const CREATE_TEAM_REQUEST = "CREATE_TEAM_REQUEST";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILURE = "CREATE_TEAM_FAILURE";
export const JOIN_TEAM_REQUEST = "JOIN_TEAM_REQUEST";
export const JOIN_TEAM_SUCCESS = "JOIN_TEAM_SUCCESS";
export const JOIN_TEAM_FAILURE = "JOIN_TEAM_FAILURE";

export const FETCH_POSTS_FEED_REQUEST = "FETCH_POSTS_FEED_REQUEST";
export const FETCH_POSTS_FEED_SUCCESS = "FETCH_POSTS_FEED_SUCCESS";
export const FETCH_POSTS_FEED_FAILURE = "FETCH_POSTS_FEED_FAILURE";
export const FETCH_TEAM_POSTS_REQUEST = "FETCH_TEAM_POSTS_REQUEST";
export const FETCH_TEAM_POSTS_SUCCESS = "FETCH_TEAM_POSTS_SUCCESS";
export const FETCH_TEAM_POSTS_FAILURE = "FETCH_TEAM_POSTS_FAILURE";
export const FETCH_POST_DETAIL_REQUEST = "FETCH_POST_DETAIL_REQUEST";
export const FETCH_POST_DETAIL_SUCCESS = "FETCH_POST_DETAIL_SUCCESS";
export const FETCH_POST_DETAIL_FAILURE = "FETCH_POST_DETAIL_FAILURE";
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";
// New Post Actions
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const FETCH_EVENTS_FEED_REQUEST = "FETCH_EVENTS_FEED_REQUEST";
export const FETCH_EVENTS_FEED_SUCCESS = "FETCH_EVENTS_FEED_SUCCESS";
export const FETCH_EVENTS_FEED_FAILURE = "FETCH_EVENTS_FEED_FAILURE";
export const FETCH_TEAM_EVENTS_REQUEST = "FETCH_TEAM_EVENTS_REQUEST";
export const FETCH_TEAM_EVENTS_SUCCESS = "FETCH_TEAM_EVENTS_SUCCESS";
export const FETCH_TEAM_EVENTS_FAILURE = "FETCH_TEAM_EVENTS_FAILURE";
// New Event Actions
export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";
